// Curated list of common 5-letter English words. Doubles as both the
// answer pool (today's word = WORD_LIST[puzzleNumber % WORD_LIST.length])
// and the accepted-guess dictionary. Kept to well-known words so every
// entry is guessable without being obscure.
const RAW_WORDS = [
  "about", "above", "actor", "acute", "admit", "adopt", "adult", "after", "again", "agent",
  "agree", "ahead", "alarm", "album", "alert", "alike", "alive", "allow", "alone", "along",
  "alter", "among", "angel", "anger", "angle", "angry", "apart", "apple", "apply", "arena",
  "argue", "arise", "armor", "aside", "asset", "avoid", "awake", "award", "aware", "badly",
  "baker", "basic", "basis", "beach", "began", "begin", "being", "below", "bench", "birth",
  "black", "blade", "blame", "blank", "blast", "blend", "blind", "block", "blood", "board",
  "boost", "booth", "bound", "brain", "brand", "brass", "brave", "bread", "break", "breed",
  "brief", "bring", "broad", "broke", "brown", "brush", "build", "built", "burst", "buyer",
  "cabin", "cable", "carry", "catch", "cause", "chain", "chair", "chalk", "champ", "chaos",
  "charm", "chart", "chase", "cheap", "check", "cheek", "cheer", "chess", "chest", "chief",
  "child", "chill", "choir", "chose", "chunk", "civic", "civil", "claim", "class", "clean",
  "clear", "clerk", "click", "cliff", "climb", "cling", "clock", "close", "cloth", "cloud",
  "clown", "coach", "coast", "could", "count", "court", "cover", "crack", "craft", "crash",
  "crazy", "cream", "crime", "crisp", "cross", "crowd", "crown", "crude", "cruel", "crush",
  "curve", "cycle", "daily", "dance", "dealt", "death", "debut", "decay", "delay", "depth",
  "diary", "digit", "dirty", "doubt", "dozen", "draft", "drama", "drawn", "dread", "dream",
  "dress", "dried", "drift", "drink", "drive", "drove", "dying", "eager", "eagle", "early",
  "earth", "eight", "elbow", "elder", "elect", "elite", "empty", "enemy", "enjoy", "enter",
  "entry", "equal", "error", "essay", "event", "every", "exact", "exist", "extra", "fable",
  "faith", "false", "fancy", "fatal", "fault", "favor", "fence", "fewer", "fiber", "field",
  "fifth", "fifty", "fight", "final", "first", "fixed", "flame", "flash", "fleet", "flesh",
  "float", "flock", "flood", "floor", "flour", "fluid", "focus", "force", "forge", "forth",
  "forty", "forum", "found", "frame", "fraud", "fresh", "front", "frost", "fruit", "fully",
  "funny", "gauge", "ghost", "giant", "given", "glass", "gleam", "globe", "glory", "glove",
  "going", "grace", "grade", "grain", "grand", "grant", "grape", "graph", "grasp", "grass",
  "grave", "great", "greed", "green", "greet", "grief", "grill", "grind", "groom", "gross",
  "group", "grove", "growl", "grown", "guard", "guess", "guest", "guide", "habit", "happy",
  "harsh", "heart", "heavy", "hence", "house", "human", "humor", "hurry", "ideal", "image",
  "imply", "index", "inner", "input", "issue", "ivory", "jumbo", "knife", "knock", "known",
  "label", "labor", "laden", "large", "laser", "later", "laugh", "layer", "learn", "lease",
  "least", "leave", "legal", "level", "light", "limit", "links", "lived", "liver", "local",
  "logic", "loose", "lower", "loyal", "lucky", "lunar", "lunch", "lying", "magic", "major",
  "maker", "march", "match", "maybe", "mayor", "meant", "medal", "media", "metal", "meter",
  "might", "minor", "minus", "mixed", "model", "moist", "money", "month", "moral", "motor",
  "mount", "mouse", "mouth", "moved", "movie", "music", "needs", "never", "newly", "night",
  "noble", "noise", "north", "noted", "novel", "nurse", "ocean", "offer", "often", "order",
  "other", "ought", "ounce", "outer", "owner", "paint", "panel", "panic", "paper", "party",
  "patch", "pause", "peace", "phase", "phone", "photo", "piece", "pilot", "pitch", "place",
  "plain", "plane", "plant", "plate", "point", "pound", "power", "press", "price", "pride",
  "prime", "print", "prior", "prize", "proof", "proud", "prove", "queen", "quick", "quiet",
  "quite", "radio", "raise", "range", "rapid", "ratio", "reach", "ready", "realm", "rebel",
  "refer", "relax", "reply", "right", "rigid", "rival", "river", "robot", "rough", "round",
  "route", "royal", "rural", "sadly", "safer", "saint", "salad", "sauce", "scale", "scare",
  "scene", "scope", "score", "sense", "serve", "seven", "shade", "shake", "shall", "shame",
  "shape", "share", "sharp", "sheep", "sheet", "shelf", "shell", "shift", "shine", "shirt",
  "shock", "shoot", "shore", "short", "shown", "sight", "since", "sixth", "sized", "skill",
  "sleep", "slide", "slope", "small", "smart", "smell", "smile", "smoke", "snake", "solid",
  "solve", "sorry", "sound", "south", "space", "spare", "spark", "speak", "speed", "spend",
  "spent", "split", "spoke", "sport", "spray", "squad", "stack", "staff", "stage", "stake",
  "stand", "start", "state", "steam", "steel", "steep", "stick", "stiff", "still", "stock",
  "stone", "store", "storm", "story", "strip", "stuck", "study", "stuff", "style", "sugar",
  "suite", "super", "sweet", "swift", "swing", "sword", "table", "taken", "taste", "teach",
  "terms", "thank", "theme", "there", "thick", "thief", "thing", "think", "third", "those",
  "three", "threw", "throw", "thumb", "tiger", "tight", "timer", "tired", "title", "today",
  "token", "topic", "total", "touch", "tough", "tower", "track", "trade", "trail", "train",
  "trait", "trash", "treat", "trend", "trial", "tribe", "trick", "tried", "tries", "truck",
  "truly", "trunk", "trust", "truth", "twice", "twist", "ultra", "uncle", "under", "union",
  "unite", "unity", "until", "upper", "upset", "urban", "usage", "usual", "valid", "value",
  "video", "virus", "visit", "vital", "vivid", "vocal", "voice", "waste", "watch", "water",
  "weigh", "weird", "wheel", "where", "which", "while", "white", "whole", "whose", "woman",
  "world", "worry", "worse", "worst", "worth", "would", "wound", "write", "wrong", "wrote",
  "yield", "young", "youth",
];

// De-duplicated and defensively filtered to exactly 5 lowercase letters, in
// case a typo ever slips into the raw list above.
export const WORD_LIST: string[] = Array.from(new Set(RAW_WORDS)).filter(
  (word) => /^[a-z]{5}$/.test(word),
);
